require 'rmagick'
require 'yaml'
require 'digest'
require 'fileutils'
require 'dotenv/load'

require 'wrsr_skinner/logo'
require 'wrsr_skinner/brand'
require 'wrsr_skinner/skinnable'
require 'wrsr_skinner/texture_wrapper'
require 'wrsr_skinner/resolver'
require 'wrsr_skinner/mod_wrapper'
require 'wrsr_skinner/region_geom'
